# Name of the workflow
name: Python CI

# Triggers: when to run this workflow
on: 
  push:
  pull_request:

# Jobs to perform
jobs:
  test:
    # Use latest Ubuntu runner
    runs-on: ubuntu-latest

    # Define multiple Python versions to test against
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    # The actual steps to perform
    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests using pytest
      - name: Run tests
        run: pytest

